context:
  name: htmlmin2
  version: "0.1.13"
  python_min: "3.9"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  # pypi doesn't provide sdist
  url: https://github.com/wilhelmer/htmlmin/archive/refs/tags/v${{ version }}.tar.gz
  sha256: a0cbbd6634166ea8dfc16d0744d06f3205d51b86d539d0114decfb3f8fd85b41

build:
  noarch: python
  python:
    entry_points:
      - htmlmin = htmlmin.command:main
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
  run_constraints:
    - htmlmin <0.0.0a0

tests:
  - python:
      imports:
      - htmlmin
      pip_check: true
      python_version: ${{ python_min }}
  - script: htmlmin -h

about:
  homepage: https://github.com/wilhelmer/htmlmin
  summary: A configurable HTML Minifier with safety features
  license: BSD-3-Clause
  license_file: LICENSE
  repository: https://github.com/wilhelmer/htmlmin

extra:
  recipe-maintainers:
    - pavelzw
